import type {
  AIRiskAssessment,
  Alert,
  AlertHistoryEntry,
  AlertRule,
  ApprovalRequest,
  DeliveryAttempt,
  EmergencyEvent,
  EscalationPolicy,
  Notification,
  NotificationChannel,
  NotificationQueueItem,
  PushSubscriptionRecord,
  SLAEvent,
  UserPreference,
  NotificationStreamRow,
} from "./types";

export const ALERTS: Alert[] = [
  {
    id: "alert-em-1",
    type: "emergency",
    priority: "critical",
    sourceEntityId: "WO-3021",
    sourceEntityType: "work_order",
    objectAddress: "БЦ Север",
    elevatorFactoryNumber: "SC-88420",
    status: "escalated",
    createdAt: "2026-05-12T09:14:00.000Z",
    updatedAt: "2026-05-12T09:20:00.000Z",
    dedupeKey: "emergency:WO-3021",
    slaEventId: "sla-1",
    escalationPolicyId: "esc-emergency",
  },
  {
    id: "alert-sync-1",
    type: "sync_failure",
    priority: "high",
    sourceEntityId: "media-4",
    sourceEntityType: "sync",
    objectAddress: "ул. Кирова, 18к2",
    elevatorFactoryNumber: "OT-441121",
    status: "unread",
    createdAt: "2026-05-12T09:08:00.000Z",
    updatedAt: "2026-05-12T09:15:00.000Z",
    dedupeKey: "sync:media-4",
    escalationPolicyId: "esc-sync",
  },
  {
    id: "alert-approval-1",
    type: "approval_request",
    priority: "high",
    sourceEntityId: "apr-1",
    sourceEntityType: "approval",
    objectAddress: "ТРЦ Восток",
    elevatorFactoryNumber: "KN-77120",
    status: "in_progress",
    createdAt: "2026-05-12T09:02:00.000Z",
    updatedAt: "2026-05-12T09:10:00.000Z",
    dedupeKey: "approval:motor:WO-3018",
    escalationPolicyId: "esc-approval",
  },
  {
    id: "alert-sla-1",
    type: "sla",
    priority: "critical",
    sourceEntityId: "WO-3011",
    sourceEntityType: "work_order",
    objectAddress: "ЖК Речной",
    elevatorFactoryNumber: "OT-11902",
    status: "unread",
    createdAt: "2026-05-12T08:55:00.000Z",
    updatedAt: "2026-05-12T09:18:00.000Z",
    dedupeKey: "sla:WO-3011",
    slaEventId: "sla-2",
    escalationPolicyId: "esc-sla",
  },
  {
    id: "alert-stock-1",
    type: "low_stock",
    priority: "medium",
    sourceEntityId: "mat-dr44",
    sourceEntityType: "warehouse",
    objectAddress: "Главный склад",
    status: "acknowledged",
    createdAt: "2026-05-12T08:40:00.000Z",
    updatedAt: "2026-05-12T09:00:00.000Z",
    dedupeKey: "stock:DR-44",
    escalationPolicyId: "esc-stock",
  },
  {
    id: "alert-ai-1",
    type: "ai_anomaly",
    priority: "medium",
    sourceEntityId: "ai-repeat-door",
    sourceEntityType: "ai",
    objectAddress: "БЦ Север",
    elevatorFactoryNumber: "SC-88420",
    status: "unread",
    createdAt: "2026-05-12T09:12:00.000Z",
    updatedAt: "2026-05-12T09:12:00.000Z",
    dedupeKey: "ai:door:SC-88420",
    escalationPolicyId: "esc-ai",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    alertId: "alert-em-1",
    priority: "critical",
    type: "emergency",
    title: "Авария не принята 5 минут",
    body: "WO-3021 требует подтверждения механиком и контроля диспетчера",
    source: "Dispatch intake",
    objectAddress: "БЦ Север",
    elevatorFactoryNumber: "SC-88420",
    assignedUser: "Мария Диспетчер",
    assignedRole: "dispatcher",
    createdAt: "2026-05-12T09:14:00.000Z",
    status: "escalated",
    channels: ["in_app", "push", "email"],
    sensitive: false,
    actionUrl: "/work-orders/WO-3021",
  },
  {
    id: "notif-2",
    alertId: "alert-sync-1",
    priority: "high",
    type: "sync_failure",
    title: "Фото аварии не отправлено",
    body: "media-4 застрял в upload queue, требуется recovery",
    source: "Offline sync engine",
    objectAddress: "ул. Кирова, 18к2",
    elevatorFactoryNumber: "OT-441121",
    assignedUser: "Алексей Климов",
    assignedRole: "mechanic",
    createdAt: "2026-05-12T09:08:00.000Z",
    status: "unread",
    channels: ["in_app", "push"],
    sensitive: false,
    actionUrl: "/sync?media=media-4",
  },
  {
    id: "notif-3",
    alertId: "alert-approval-1",
    priority: "high",
    type: "approval_request",
    title: "Списание двигателя требует approval",
    body: "Механик списал двигатель стоимостью 148 000 ₽",
    source: "Warehouse approvals",
    objectAddress: "ТРЦ Восток",
    elevatorFactoryNumber: "KN-77120",
    assignedUser: "Руководитель участка",
    assignedRole: "supervisor",
    createdAt: "2026-05-12T09:02:00.000Z",
    status: "in_progress",
    channels: ["in_app", "push", "email"],
    sensitive: true,
    actionUrl: "/warehouse?approval=apr-1",
  },
  {
    id: "notif-4",
    alertId: "alert-sla-1",
    priority: "critical",
    type: "sla",
    title: "SLA breach через 7 минут",
    body: "Аварийная заявка WO-3011 приближается к нарушению SLA",
    source: "SLA timer",
    objectAddress: "ЖК Речной",
    elevatorFactoryNumber: "OT-11902",
    assignedUser: "Ирина Соколова",
    assignedRole: "mechanic",
    createdAt: "2026-05-12T08:55:00.000Z",
    status: "unread",
    channels: ["in_app", "push", "sms"],
    sensitive: false,
    actionUrl: "/mechanic?wo=WO-3011",
  },
  {
    id: "notif-5",
    alertId: "alert-stock-1",
    priority: "medium",
    type: "low_stock",
    title: "DR-44 ниже минимума",
    body: "Остаток доступно 4 шт. при min 24",
    source: "Warehouse stock monitor",
    objectAddress: "Главный склад",
    assignedUser: "Олег Романов",
    assignedRole: "supervisor",
    createdAt: "2026-05-12T08:40:00.000Z",
    status: "acknowledged",
    channels: ["in_app"],
    sensitive: false,
    actionUrl: "/warehouse?material=DR-44",
  },
  {
    id: "notif-6",
    alertId: "alert-ai-1",
    priority: "medium",
    type: "ai_anomaly",
    title: "AI anomaly: repeat door failures",
    body: "SC-88420 показывает повторные аварии дверей выше baseline",
    source: "AI diagnostics",
    objectAddress: "БЦ Север",
    elevatorFactoryNumber: "SC-88420",
    assignedUser: "Руководитель участка",
    assignedRole: "supervisor",
    createdAt: "2026-05-12T09:12:00.000Z",
    status: "unread",
    channels: ["in_app", "email"],
    sensitive: false,
    actionUrl: "/dashboard?ai=door",
  },
];

export const ALERT_RULES: AlertRule[] = [
  {
    id: "rule-emergency-unaccepted",
    name: "Emergency not accepted",
    type: "emergency",
    condition: "work_order.type=emergency AND accepted_at IS NULL after 5m",
    priority: "critical",
    channels: ["in_app", "push", "email"],
    throttleMinutes: 0,
    dedupeWindowMinutes: 10,
    enabled: true,
  },
  {
    id: "rule-sla-risk",
    name: "SLA timer warning",
    type: "sla",
    condition: "remaining_minutes <= 15 OR breach_at <= now()+15m",
    priority: "critical",
    channels: ["in_app", "push", "sms"],
    throttleMinutes: 2,
    dedupeWindowMinutes: 5,
    enabled: true,
  },
  {
    id: "rule-sync-stuck",
    name: "Stuck upload queue",
    type: "sync_failure",
    condition: "upload.status=failed OR retry_count > 3",
    priority: "high",
    channels: ["in_app", "push"],
    throttleMinutes: 5,
    dedupeWindowMinutes: 15,
    enabled: true,
  },
  {
    id: "rule-approval-high-cost",
    name: "High cost approval",
    type: "approval_request",
    condition: "material_writeoff.amount > 100000",
    priority: "high",
    channels: ["in_app", "push", "email"],
    throttleMinutes: 1,
    dedupeWindowMinutes: 30,
    enabled: true,
  },
];

export const ESCALATION_POLICIES: EscalationPolicy[] = [
  {
    id: "esc-emergency",
    name: "Emergency response ladder",
    alertType: "emergency",
    steps: [
      {
        level: "mechanic",
        afterMinutes: 0,
        channels: ["push", "in_app"],
        action: "fullscreen PWA push with accept/open-route actions",
      },
      {
        level: "dispatcher",
        afterMinutes: 5,
        channels: ["in_app", "push"],
        action: "dispatcher command-center alert",
      },
      {
        level: "supervisor",
        afterMinutes: 10,
        channels: ["push", "email"],
        action: "supervisor escalation",
      },
      {
        level: "director",
        afterMinutes: 20,
        channels: ["email", "sms"],
        action: "director SLA breach notification",
      },
    ],
  },
  {
    id: "esc-sync",
    name: "Sync recovery ladder",
    alertType: "sync_failure",
    steps: [
      {
        level: "mechanic",
        afterMinutes: 0,
        channels: ["in_app", "push"],
        action: "show recovery action",
      },
      {
        level: "supervisor",
        afterMinutes: 30,
        channels: ["in_app", "email"],
        action: "supervisor stale media alert",
      },
    ],
  },
  {
    id: "esc-approval",
    name: "Approval manager chain",
    alertType: "approval_request",
    steps: [
      {
        level: "supervisor",
        afterMinutes: 0,
        channels: ["in_app", "push", "email"],
        action: "approval request",
      },
      {
        level: "director",
        afterMinutes: 60,
        channels: ["email", "sms"],
        action: "approval escalation",
      },
    ],
  },
  {
    id: "esc-sla",
    name: "SLA breach ladder",
    alertType: "sla",
    steps: [
      {
        level: "mechanic",
        afterMinutes: 0,
        channels: ["push", "in_app"],
        action: "countdown push",
      },
      {
        level: "dispatcher",
        afterMinutes: 3,
        channels: ["in_app"],
        action: "dispatch reroute",
      },
      {
        level: "supervisor",
        afterMinutes: 7,
        channels: ["push", "email"],
        action: "SLA risk owner",
      },
    ],
  },
];

export const NOTIFICATION_CHANNELS: NotificationChannel[] = [
  {
    id: "ch-inapp",
    type: "in_app",
    name: "Realtime in-app stream",
    enabled: true,
    deliverySlaSeconds: 1,
    retryPolicy: "websocket + event replay",
  },
  {
    id: "ch-push",
    type: "push",
    name: "PWA Push API",
    enabled: true,
    deliverySlaSeconds: 5,
    retryPolicy: "service worker delivery retry",
  },
  {
    id: "ch-email",
    type: "email",
    name: "Email escalation",
    enabled: true,
    deliverySlaSeconds: 60,
    retryPolicy: "queued provider retry",
  },
  {
    id: "ch-sms",
    type: "sms",
    name: "SMS future channel",
    enabled: false,
    deliverySlaSeconds: 20,
    retryPolicy: "provider failover",
  },
  {
    id: "ch-telegram",
    type: "telegram",
    name: "Telegram future channel",
    enabled: false,
    deliverySlaSeconds: 10,
    retryPolicy: "bot queue retry",
  },
];

export const PUSH_SUBSCRIPTIONS: PushSubscriptionRecord[] = [
  {
    id: "push-1",
    userId: "mech-014",
    deviceId: "iphone-14-mech-014",
    endpointHash: "sha256:push:014",
    pwaInstall: true,
    emergencyFullscreen: true,
    actionsEnabled: true,
    lastSeenAt: "2026-05-12T09:19:00.000Z",
  },
  {
    id: "push-2",
    userId: "disp-002",
    deviceId: "desktop-dispatch",
    endpointHash: "sha256:push:disp",
    pwaInstall: true,
    emergencyFullscreen: false,
    actionsEnabled: true,
    lastSeenAt: "2026-05-12T09:20:00.000Z",
  },
];

export const NOTIFICATION_QUEUE: NotificationQueueItem[] = [
  {
    id: "queue-1",
    notificationId: "notif-1",
    channel: "push",
    priority: "critical",
    status: "delivered",
    attempts: 1,
    lockedBy: "push-worker-1",
  },
  {
    id: "queue-2",
    notificationId: "notif-1",
    channel: "email",
    priority: "critical",
    status: "sent",
    attempts: 1,
    lockedBy: "mail-worker-2",
  },
  {
    id: "queue-3",
    notificationId: "notif-2",
    channel: "push",
    priority: "high",
    status: "failed",
    attempts: 3,
    nextAttemptAt: "2026-05-12T09:24:00.000Z",
    lockedBy: "push-worker-1",
  },
  {
    id: "queue-4",
    notificationId: "notif-4",
    channel: "sms",
    priority: "critical",
    status: "queued",
    attempts: 0,
    nextAttemptAt: "2026-05-12T09:21:00.000Z",
  },
];

export const SLA_EVENTS: SLAEvent[] = [
  {
    id: "sla-1",
    workOrderId: "WO-3021",
    objectAddress: "БЦ Север",
    elevatorFactoryNumber: "SC-88420",
    dueAt: "2026-05-12T09:45:00.000Z",
    warnAt: "2026-05-12T09:30:00.000Z",
    breachAt: "2026-05-12T09:45:00.000Z",
    remainingMinutes: 25,
    risk: "escalated",
  },
  {
    id: "sla-2",
    workOrderId: "WO-3011",
    objectAddress: "ЖК Речной",
    elevatorFactoryNumber: "OT-11902",
    dueAt: "2026-05-12T09:28:00.000Z",
    warnAt: "2026-05-12T09:13:00.000Z",
    breachAt: "2026-05-12T09:28:00.000Z",
    remainingMinutes: 7,
    risk: "breach",
  },
];

export const EMERGENCY_EVENTS: EmergencyEvent[] = [
  {
    id: "em-1",
    workOrderId: "WO-3021",
    objectAddress: "БЦ Север",
    elevatorFactoryNumber: "SC-88420",
    receivedAt: "2026-05-12T09:14:00.000Z",
    dispatcher: "Мария Диспетчер",
    mechanic: "Алексей Климов",
    escalationPolicyId: "esc-emergency",
    fullscreenPushSent: true,
  },
];

export const APPROVAL_REQUESTS: ApprovalRequest[] = [
  {
    id: "apr-1",
    type: "high_cost_part",
    requester: "Павел Механик",
    approverChain: ["Руководитель участка", "Директор"],
    amount: "148 000 ₽",
    status: "pending",
    createdAt: "2026-05-12T09:02:00.000Z",
    dueAt: "2026-05-12T10:02:00.000Z",
  },
  {
    id: "apr-2",
    type: "unsafe_closure",
    requester: "Алексей Климов",
    approverChain: ["Руководитель участка"],
    status: "escalated",
    createdAt: "2026-05-12T08:30:00.000Z",
    dueAt: "2026-05-12T09:00:00.000Z",
  },
];

export const USER_PREFERENCES: UserPreference[] = [
  {
    userId: "mech-014",
    quietHours: { enabled: true, start: "22:00", end: "07:00" },
    enabledAlertTypes: ["emergency", "sla", "sync_failure", "approval_request"],
    channels: ["in_app", "push"],
    sound: true,
    vibration: true,
    emergencyOverride: true,
    escalationPreference: "aggressive",
  },
  {
    userId: "supervisor-001",
    quietHours: { enabled: true, start: "23:00", end: "06:00" },
    enabledAlertTypes: [
      "emergency",
      "sla",
      "approval_request",
      "ai_anomaly",
      "low_stock",
    ],
    channels: ["in_app", "push", "email"],
    sound: true,
    vibration: false,
    emergencyOverride: true,
    escalationPreference: "normal",
  },
];

export const ALERT_HISTORY: AlertHistoryEntry[] = [
  {
    id: "hist-1",
    alertId: "alert-em-1",
    actor: "alert-engine",
    action: "created",
    createdAt: "2026-05-12T09:14:00.000Z",
    details: "Emergency alert created from dispatch intake",
  },
  {
    id: "hist-2",
    alertId: "alert-em-1",
    actor: "push-worker",
    action: "sent",
    channel: "push",
    createdAt: "2026-05-12T09:14:02.000Z",
    details: "Fullscreen push sent to mechanic",
  },
  {
    id: "hist-3",
    alertId: "alert-em-1",
    actor: "escalation-engine",
    action: "escalated",
    channel: "in_app",
    createdAt: "2026-05-12T09:19:00.000Z",
    details: "Escalated to dispatcher after 5 minutes",
  },
  {
    id: "hist-4",
    alertId: "alert-sync-1",
    actor: "delivery-worker",
    action: "failed",
    channel: "push",
    createdAt: "2026-05-12T09:15:00.000Z",
    details: "Push endpoint temporarily unavailable",
  },
];

export const DELIVERY_ATTEMPTS: DeliveryAttempt[] = [
  {
    id: "da-1",
    notificationId: "notif-1",
    channel: "push",
    status: "delivered",
    attemptedAt: "2026-05-12T09:14:02.000Z",
    latencyMs: 940,
  },
  {
    id: "da-2",
    notificationId: "notif-2",
    channel: "push",
    status: "failed",
    attemptedAt: "2026-05-12T09:15:00.000Z",
    latencyMs: 5000,
    error: "device offline",
  },
  {
    id: "da-3",
    notificationId: "notif-3",
    channel: "email",
    status: "delivered",
    attemptedAt: "2026-05-12T09:02:10.000Z",
    latencyMs: 1840,
  },
];

export const AI_RISK_ASSESSMENTS: AIRiskAssessment[] = [
  {
    id: "risk-1",
    alertId: "alert-em-1",
    score: 94,
    category: "customer_impact",
    explanation: "Emergency unaccepted with passenger complaint history",
    recommendation: "Escalate dispatcher now and prepare supervisor fallback",
  },
  {
    id: "risk-2",
    alertId: "alert-sync-1",
    score: 78,
    category: "sync_risk",
    explanation: "Emergency media evidence stuck for 11 minutes",
    recommendation:
      "Retry push warning, then supervisor alert after 30 minutes",
  },
  {
    id: "risk-3",
    alertId: "alert-approval-1",
    score: 86,
    category: "fraud",
    explanation: "High-cost part write-off outside normal mechanic baseline",
    recommendation: "Require supervisor approval and photo evidence review",
  },
  {
    id: "risk-4",
    alertId: "alert-stock-1",
    score: 72,
    category: "stockout",
    explanation: "DR-44 stock may block two emergency door repairs",
    recommendation: "Trigger purchase request and warehouse alert",
  },
];

export function buildNotificationStreamRows(): NotificationStreamRow[] {
  return NOTIFICATIONS.map((notification) => {
    const alert = ALERTS.find(
      (candidate) => candidate.id === notification.alertId,
    );
    return {
      notification,
      alert,
      sla: alert?.slaEventId
        ? SLA_EVENTS.find((sla) => sla.id === alert.slaEventId)
        : undefined,
      queueItems: NOTIFICATION_QUEUE.filter(
        (item) => item.notificationId === notification.id,
      ),
      ai: AI_RISK_ASSESSMENTS.find(
        (risk) => risk.alertId === notification.alertId,
      ),
    };
  });
}
