import type {
  AuditReport,
  DocumentAiWarning,
  DocumentGridRow,
  ExportJob,
  GeneratedDocument,
  GenerationLog,
  InspectionReport,
  PdfFile,
  PrintJob,
  ReportPermission,
  ReportTemplate,
  ReportVersion,
  ScheduledReport,
  ServiceAct,
  SignatureBlock,
  WorkOrderReport,
} from "./types";

export const REPORT_TEMPLATES: ReportTemplate[] = [
  {
    id: "tpl-work-order-v5",
    name: "Заказ-наряд с фотофиксацией",
    documentType: "work_order",
    version: 5,
    locale: "ru-RU",
    brandProfile: "neolift-industrial",
    blocks: [
      "branding",
      "dynamic_fields",
      "table",
      "photo_evidence",
      "signature",
      "qr",
    ],
    supportsPrint: true,
    supportsQr: true,
    photoRequired: true,
    enabled: true,
  },
  {
    id: "tpl-service-act-v3",
    name: "Акт выполненных работ",
    documentType: "service_act",
    version: 3,
    locale: "ru-RU",
    brandProfile: "neolift-customer",
    blocks: ["branding", "dynamic_fields", "table", "signature", "qr"],
    supportsPrint: true,
    supportsQr: true,
    photoRequired: false,
    enabled: true,
  },
  {
    id: "tpl-inspection-v4",
    name: "Отчет проверки лифта",
    documentType: "inspection_report",
    version: 4,
    locale: "ru-RU",
    brandProfile: "neolift-compliance",
    blocks: [
      "branding",
      "dynamic_fields",
      "table",
      "photo_evidence",
      "signature",
      "compliance_note",
      "qr",
    ],
    supportsPrint: true,
    supportsQr: true,
    photoRequired: true,
    enabled: true,
  },
  {
    id: "tpl-warehouse-v2",
    name: "Складской отчет списаний",
    documentType: "material_writeoff_act",
    version: 2,
    locale: "ru-RU",
    brandProfile: "neolift-warehouse",
    blocks: ["branding", "dynamic_fields", "table", "signature", "qr"],
    supportsPrint: true,
    supportsQr: true,
    photoRequired: false,
    enabled: true,
  },
];

export const GENERATED_DOCUMENTS: GeneratedDocument[] = [
  {
    id: "doc-wo-3021",
    documentType: "work_order",
    title: "Заказ-наряд WO-3021",
    objectId: "obj-sever",
    objectAddress: "БЦ Север",
    customerName: "УК Север",
    elevatorId: "el-sc88420",
    elevatorFactoryNumber: "SC-88420",
    workOrderId: "WO-3021",
    mechanicName: "Алексей Климов",
    createdAt: "2026-05-12T09:40:00.000Z",
    generatedAt: "2026-05-12T09:42:00.000Z",
    version: 3,
    generationStatus: "ready",
    signatureStatus: "customer_signed",
    exportStatus: "sent",
    templateId: "tpl-work-order-v5",
    pdfFileId: "pdf-wo-3021",
    storageTier: "hot",
    immutable: true,
  },
  {
    id: "doc-act-may-sever",
    documentType: "service_act",
    title: "Акт за май · УК Север",
    objectId: "obj-sever",
    objectAddress: "БЦ Север",
    customerName: "УК Север",
    createdAt: "2026-05-12T08:00:00.000Z",
    version: 1,
    generationStatus: "rendering",
    signatureStatus: "pending",
    exportStatus: "queued",
    templateId: "tpl-service-act-v3",
    storageTier: "hot",
    immutable: false,
  },
  {
    id: "doc-insp-118",
    documentType: "inspection_report",
    title: "Проверка INSP-118",
    objectId: "obj-kir18",
    objectAddress: "ул. Кирова, 18к2",
    customerName: "ТСЖ Кирова",
    elevatorId: "el-ot441121",
    elevatorFactoryNumber: "OT-441121",
    workOrderId: "WO-2951",
    mechanicName: "Ирина Соколова",
    createdAt: "2026-05-11T16:20:00.000Z",
    generatedAt: "2026-05-11T16:25:00.000Z",
    version: 2,
    generationStatus: "ready",
    signatureStatus: "manager_approved",
    exportStatus: "downloaded",
    templateId: "tpl-inspection-v4",
    pdfFileId: "pdf-insp-118",
    storageTier: "warm",
    immutable: true,
  },
  {
    id: "doc-writeoff-77",
    documentType: "material_writeoff_act",
    title: "Акт списания двигателя",
    objectId: "obj-vostok",
    objectAddress: "ТРЦ Восток",
    customerName: "ТРЦ Восток",
    elevatorId: "el-kn77120",
    elevatorFactoryNumber: "KN-77120",
    workOrderId: "WO-3018",
    mechanicName: "Павел Механик",
    createdAt: "2026-05-12T09:02:00.000Z",
    version: 1,
    generationStatus: "failed",
    signatureStatus: "pending",
    exportStatus: "failed",
    templateId: "tpl-warehouse-v2",
    storageTier: "hot",
    immutable: false,
  },
  {
    id: "doc-sla-week",
    documentType: "sla_report",
    title: "SLA отчет за неделю",
    objectId: "all",
    objectAddress: "Все объекты",
    customerName: "НеоЛифт",
    createdAt: "2026-05-12T07:00:00.000Z",
    generatedAt: "2026-05-12T07:04:00.000Z",
    version: 6,
    generationStatus: "ready",
    signatureStatus: "digitally_signed",
    exportStatus: "sent",
    templateId: "tpl-service-act-v3",
    pdfFileId: "pdf-sla-week",
    storageTier: "archive",
    immutable: true,
  },
];

export const WORK_ORDER_REPORTS: WorkOrderReport[] = [
  {
    id: "wor-1",
    documentId: "doc-wo-3021",
    workOrderId: "WO-3021",
    workSummary: "Устранение аварии дверей, проверка датчиков, тестовый прогон",
    materialRows: 3,
    photoEvidenceIds: ["media-1", "media-2", "media-3"],
    signatureBlockIds: ["sig-1", "sig-2"],
    closeReady: true,
  },
  {
    id: "wor-2",
    documentId: "doc-writeoff-77",
    workOrderId: "WO-3018",
    workSummary: "Замена двигателя привода дверей",
    materialRows: 1,
    photoEvidenceIds: ["media-8"],
    signatureBlockIds: ["sig-5"],
    closeReady: false,
  },
];

export const SERVICE_ACTS: ServiceAct[] = [
  {
    id: "act-1",
    documentId: "doc-act-may-sever",
    periodStart: "2026-05-01",
    periodEnd: "2026-05-31",
    customerName: "УК Север",
    workOrdersIncluded: 42,
    totalAmount: "482 000 ₽",
    signedByCustomer: false,
  },
];

export const AUDIT_REPORTS: AuditReport[] = [
  {
    id: "audit-1",
    documentId: "doc-sla-week",
    auditScope: "sla",
    findings: 8,
    criticalFindings: 2,
    correctiveActions: 5,
  },
];

export const INSPECTION_REPORTS: InspectionReport[] = [
  {
    id: "insp-1",
    documentId: "doc-insp-118",
    inspectionId: "INSP-118",
    checklistItems: 64,
    failedItems: 3,
    nextInspectionAt: "2026-08-11T09:00:00.000Z",
  },
];

export const PDF_FILES: PdfFile[] = [
  {
    id: "pdf-wo-3021",
    documentId: "doc-wo-3021",
    fileName: "WO-3021-neolift-act.pdf",
    pageCount: 7,
    sizeMb: 12.4,
    s3Key: "s3://neolift-docs/hot/2026/05/WO-3021-v3.pdf",
    thumbnailKey: "thumbs/reports/WO-3021-v3.webp",
    checksum: "sha256:wo3021v3",
    signedUrlExpiresAt: "2026-05-12T10:42:00.000Z",
    qrVerificationUrl: "https://verify.neolift.example/doc/wo3021v3",
  },
  {
    id: "pdf-insp-118",
    documentId: "doc-insp-118",
    fileName: "INSP-118-report.pdf",
    pageCount: 18,
    sizeMb: 24.8,
    s3Key: "s3://neolift-docs/warm/2026/05/INSP-118-v2.pdf",
    thumbnailKey: "thumbs/reports/INSP-118-v2.webp",
    checksum: "sha256:insp118v2",
    signedUrlExpiresAt: "2026-05-12T12:00:00.000Z",
    qrVerificationUrl: "https://verify.neolift.example/doc/insp118v2",
  },
  {
    id: "pdf-sla-week",
    documentId: "doc-sla-week",
    fileName: "SLA-week-19.pdf",
    pageCount: 11,
    sizeMb: 6.1,
    s3Key: "s3://neolift-docs/archive/2026/week-19/sla.pdf",
    thumbnailKey: "thumbs/reports/sla-week-19.webp",
    checksum: "sha256:slaweek19",
    signedUrlExpiresAt: "2026-05-13T07:04:00.000Z",
    qrVerificationUrl: "https://verify.neolift.example/doc/slaweek19",
  },
];

export const PRINT_JOBS: PrintJob[] = [
  {
    id: "print-1",
    documentId: "doc-wo-3021",
    printerName: "HP Office A4 · диспетчерская",
    status: "printed",
    copies: 2,
    paper: "A4",
    grayscale: true,
    marginsMm: 12,
    createdAt: "2026-05-12T09:45:00.000Z",
  },
  {
    id: "print-2",
    documentId: "doc-act-may-sever",
    printerName: "Canon C3520 · бухгалтерия",
    status: "queued",
    copies: 1,
    paper: "A4",
    grayscale: false,
    marginsMm: 10,
    createdAt: "2026-05-12T09:15:00.000Z",
  },
  {
    id: "print-3",
    documentId: "doc-writeoff-77",
    printerName: "Warehouse Zebra PDF",
    status: "failed",
    copies: 1,
    paper: "A4",
    grayscale: true,
    marginsMm: 14,
    createdAt: "2026-05-12T09:08:00.000Z",
    diagnostics: "Template failed before print spool",
  },
];

export const SIGNATURE_BLOCKS: SignatureBlock[] = [
  {
    id: "sig-1",
    documentId: "doc-wo-3021",
    signerRole: "mechanic",
    signerName: "Алексей Климов",
    status: "mechanic_signed",
    signedAt: "2026-05-12T09:39:00.000Z",
    deviceId: "iphone-14-mech-014",
  },
  {
    id: "sig-2",
    documentId: "doc-wo-3021",
    signerRole: "customer",
    signerName: "Иван Петров",
    status: "customer_signed",
    signedAt: "2026-05-12T09:41:00.000Z",
    deviceId: "ipad-customer-desk",
  },
  {
    id: "sig-3",
    documentId: "doc-act-may-sever",
    signerRole: "manager",
    signerName: "Руководитель участка",
    status: "pending",
  },
  {
    id: "sig-4",
    documentId: "doc-insp-118",
    signerRole: "manager",
    signerName: "Ольга Руководитель",
    status: "manager_approved",
    signedAt: "2026-05-11T16:24:00.000Z",
  },
  {
    id: "sig-5",
    documentId: "doc-writeoff-77",
    signerRole: "manager",
    signerName: "Олег Романов",
    status: "pending",
  },
  {
    id: "sig-6",
    documentId: "doc-sla-week",
    signerRole: "digital_certificate",
    signerName: "НеоЛифт ЭЦП",
    status: "digitally_signed",
    signedAt: "2026-05-12T07:04:00.000Z",
    certificateThumbprint: "A1:9D:77:NEO",
  },
];

export const REPORT_VERSIONS: ReportVersion[] = [
  {
    id: "ver-1",
    documentId: "doc-wo-3021",
    version: 1,
    createdAt: "2026-05-12T09:30:00.000Z",
    createdBy: "sync-engine",
    reason: "initial",
    diffSummary: "Initial work order data collected",
    pdfFileId: "pdf-wo-3021-v1",
  },
  {
    id: "ver-2",
    documentId: "doc-wo-3021",
    version: 2,
    createdAt: "2026-05-12T09:37:00.000Z",
    createdBy: "Алексей Климов",
    reason: "photo_added",
    diffSummary: "Added before/after photo evidence block",
    pdfFileId: "pdf-wo-3021-v2",
  },
  {
    id: "ver-3",
    documentId: "doc-wo-3021",
    version: 3,
    createdAt: "2026-05-12T09:42:00.000Z",
    createdBy: "document-engine",
    reason: "signature_added",
    diffSummary: "Customer signature embedded and QR verification updated",
    pdfFileId: "pdf-wo-3021",
  },
  {
    id: "ver-4",
    documentId: "doc-insp-118",
    version: 2,
    createdAt: "2026-05-11T16:25:00.000Z",
    createdBy: "Ольга Руководитель",
    reason: "correction",
    diffSummary: "Corrected failed checklist item count",
    pdfFileId: "pdf-insp-118",
  },
];

export const EXPORT_JOBS: ExportJob[] = [
  {
    id: "exp-1",
    documentIds: ["doc-wo-3021"],
    format: "pdf",
    status: "sent",
    target: "customer_portal",
    progress: 100,
    createdAt: "2026-05-12T09:43:00.000Z",
    completedAt: "2026-05-12T09:44:00.000Z",
  },
  {
    id: "exp-2",
    documentIds: ["doc-act-may-sever", "doc-sla-week"],
    format: "zip",
    status: "exporting",
    target: "archive",
    progress: 62,
    createdAt: "2026-05-12T09:12:00.000Z",
  },
  {
    id: "exp-3",
    documentIds: ["doc-writeoff-77"],
    format: "pdf",
    status: "failed",
    target: "email",
    progress: 18,
    createdAt: "2026-05-12T09:06:00.000Z",
    error: "Missing manager signature block",
  },
];

export const SCHEDULED_REPORTS: ScheduledReport[] = [
  {
    id: "sched-1",
    name: "Ежемесячные акты УК Север",
    documentType: "service_act",
    schedule: "monthly",
    customerName: "УК Север",
    nextRunAt: "2026-06-01T02:00:00.000Z",
    enabled: true,
    lastStatus: "ready",
  },
  {
    id: "sched-2",
    name: "SLA weekly operations",
    documentType: "sla_report",
    schedule: "weekly",
    nextRunAt: "2026-05-18T03:00:00.000Z",
    enabled: true,
    lastStatus: "ready",
  },
  {
    id: "sched-3",
    name: "Warehouse write-off pack",
    documentType: "material_writeoff_act",
    schedule: "weekly",
    nextRunAt: "2026-05-19T04:00:00.000Z",
    enabled: false,
    lastStatus: "failed",
  },
];

export const REPORT_PERMISSIONS: ReportPermission[] = [
  {
    id: "perm-1",
    documentId: "doc-wo-3021",
    scope: "mechanic",
    canView: true,
    canDownload: true,
    canPrint: true,
    canSign: true,
    redacted: false,
  },
  {
    id: "perm-2",
    documentId: "doc-wo-3021",
    scope: "customer_portal",
    canView: true,
    canDownload: true,
    canPrint: true,
    canSign: false,
    redacted: true,
  },
  {
    id: "perm-3",
    documentId: "doc-writeoff-77",
    scope: "restricted",
    canView: true,
    canDownload: false,
    canPrint: false,
    canSign: false,
    redacted: true,
  },
];

export const DOCUMENT_AI_WARNINGS: DocumentAiWarning[] = [
  {
    id: "warn-1",
    documentId: "doc-act-may-sever",
    severity: "warning",
    category: "missing_signature",
    message: "Акт ожидает подпись руководителя перед отправкой",
    recommendation: "Notify supervisor and block customer export until signed",
  },
  {
    id: "warn-2",
    documentId: "doc-writeoff-77",
    severity: "critical",
    category: "material_anomaly",
    message: "Высокая стоимость двигателя и отсутствует approval",
    recommendation:
      "Require manager approval and photo evidence before PDF generation",
  },
  {
    id: "warn-3",
    documentId: "doc-wo-3021",
    severity: "info",
    category: "template_risk",
    message: "Документ использует template v5; доступна v6 с улучшенным QR",
    recommendation:
      "Regenerate after customer delivery if corrections are needed",
  },
];

export const GENERATION_LOGS: GenerationLog[] = [
  {
    id: "log-1",
    documentId: "doc-wo-3021",
    stage: "data_collected",
    status: "ok",
    createdAt: "2026-05-12T09:40:20.000Z",
    details: "Works, materials, photos and signatures collected",
  },
  {
    id: "log-2",
    documentId: "doc-wo-3021",
    stage: "pdf_rendered",
    status: "ok",
    createdAt: "2026-05-12T09:42:00.000Z",
    details: "PDF rendered in 4.2s with 7 pages",
  },
  {
    id: "log-3",
    documentId: "doc-writeoff-77",
    stage: "failed",
    status: "error",
    createdAt: "2026-05-12T09:07:00.000Z",
    details: "Missing approval signature for high cost part",
  },
  {
    id: "log-4",
    documentId: "doc-act-may-sever",
    stage: "photos_embedded",
    status: "warning",
    createdAt: "2026-05-12T09:10:00.000Z",
    details: "Two optional photo blocks skipped for monthly act",
  },
];

export function buildDocumentGridRows(): DocumentGridRow[] {
  return GENERATED_DOCUMENTS.map((document) => ({
    document,
    pdf: PDF_FILES.find((pdf) => pdf.id === document.pdfFileId),
    signatures: SIGNATURE_BLOCKS.filter(
      (signature) => signature.documentId === document.id,
    ),
    latestVersion: REPORT_VERSIONS.filter(
      (version) => version.documentId === document.id,
    ).sort((a, b) => b.version - a.version)[0],
    exportJob: EXPORT_JOBS.find((job) => job.documentIds.includes(document.id)),
    warnings: DOCUMENT_AI_WARNINGS.filter(
      (warning) => warning.documentId === document.id,
    ),
  }));
}
