import type { ImportJob, ImportTemplate, MasterDataReference, QueueWorker } from "./types";

export const IMPORT_TEMPLATES: ImportTemplate[] = [
  {
    id: "tpl-elevators-gost-v3",
    name: "Лифты: паспорт + объект + рег. номер",
    entityType: "elevators",
    fileType: "multi_sheet_xlsx",
    version: "3.4",
    requiredFields: ["factoryNumber", "objectAddress", "manufacturer", "commissionedAt", "elevatorType"],
    optionalFields: ["controllerType", "capacityKg", "stops", "serviceContract"],
    owner: "MDM office",
    lastUsedAt: "2026-05-09T09:20:00.000Z",
  },
  {
    id: "tpl-warehouse-balances-v2",
    name: "Склад: материалы, остатки, поставщики",
    entityType: "warehouse",
    fileType: "xlsx",
    version: "2.1",
    requiredFields: ["sku", "name", "warehouse", "quantity", "unit"],
    optionalFields: ["category", "supplier", "minStock", "binLocation"],
    owner: "Warehouse control",
    lastUsedAt: "2026-05-08T17:15:00.000Z",
  },
  {
    id: "tpl-objects-sla-v5",
    name: "Объекты: адреса, заказчики, SLA",
    entityType: "objects",
    fileType: "csv",
    version: "5.0",
    requiredFields: ["address", "customer", "slaCategory", "serviceType"],
    optionalFields: ["entrance", "region", "dispatcherZone", "contractNumber"],
    owner: "Service operations",
    lastUsedAt: "2026-05-07T12:10:00.000Z",
  },
];

export const IMPORT_JOBS: ImportJob[] = [
  {
    id: "job-2847",
    number: "IMP-2026-2847",
    name: "Массовая загрузка лифтов — Южный участок",
    entityType: "elevators",
    status: "validating",
    stage: "validation",
    progress: 68,
    file: {
      id: "file-771",
      name: "lifts_south_2026_q2.xlsx",
      fileType: "multi_sheet_xlsx",
      sizeMb: 46.8,
      sheets: ["Паспорта", "Объекты", "Договоры"],
      checksum: "sha256:9d7e...a21f",
      uploadedBy: "Марина Соколова",
      uploadedAt: "2026-05-09T08:57:00.000Z",
      virusScan: "clean",
      chunkCount: 24,
    },
    dataSource: { id: "ds-legacy-1c", name: "Legacy 1C export", entityType: "elevators", origin: "legacy_erp", reliabilityScore: 86 },
    template: IMPORT_TEMPLATES[0],
    mappings: [
      { id: "map-1", sourceColumn: "Заводской №", targetField: "factoryNumber", confidence: 99, transform: "trim", required: true, status: "confirmed" },
      { id: "map-2", sourceColumn: "Адрес объекта", targetField: "object.address", confidence: 94, transform: "normalize_address", required: true, status: "auto" },
      { id: "map-3", sourceColumn: "Производитель", targetField: "manufacturerId", confidence: 88, transform: "dictionary_lookup", required: true, status: "needs_review" },
      { id: "map-4", sourceColumn: "Грузоподъемность", targetField: "capacityKg", confidence: 92, transform: "none", required: false, status: "auto" },
      { id: "map-5", sourceColumn: "Дата ввода", targetField: "commissionedAt", confidence: 81, transform: "none", required: true, status: "needs_review" },
    ],
    validationErrors: [
      { id: "err-1", row: 143, field: "factoryNumber", message: "Заводской номер уже существует на другом объекте", severity: "blocking", rule: "unique_factory_number", suggestion: "Проверить дубль или выбрать режим update" },
      { id: "err-2", row: 318, field: "object.address", message: "Адрес не нормализован ФИАС/КЛАДР", severity: "warning", rule: "address_quality", suggestion: "Принять AI-нормализацию: ул. Кирова, 18к2" },
      { id: "err-3", row: 921, field: "manufacturerId", message: "Производитель OTIS RUS не найден в MDM", severity: "blocking", rule: "reference_exists", suggestion: "Связать с Otis или создать MDM alias" },
    ],
    duplicates: [
      { id: "dup-1", row: 143, entityType: "elevators", importedValue: "ЩЛЗ-332918 / Ленина 42", existingValue: "ЩЛЗ 332918 / пр-т Ленина, 42", confidence: "critical", reason: "same factory number + normalized address distance 0.94", resolution: "manual_review" },
      { id: "dup-2", row: 319, entityType: "objects", importedValue: "БЦ Северный, Кирова 18", existingValue: "БЦ Север, ул. Кирова 18к2", confidence: "high", reason: "similar address and customer", resolution: "merge" },
    ],
    preview: [
      { id: "pr-1", row: 1, entity: "Лифт ЩЛЗ-441120", action: "create", confidence: 98, affectedObject: "ЖК Маяк", warnings: 0 },
      { id: "pr-2", row: 2, entity: "Лифт OTIS-88420", action: "update", confidence: 91, affectedObject: "БЦ Север", warnings: 1 },
      { id: "pr-3", row: 143, entity: "Лифт ЩЛЗ-332918", action: "review", confidence: 74, affectedObject: "Ленина 42", warnings: 2 },
      { id: "pr-4", row: 921, entity: "Производитель OTIS RUS", action: "reject", confidence: 65, affectedObject: "MDM manufacturers", warnings: 1 },
    ],
    rollbackSnapshot: { id: "rb-2847", jobId: "job-2847", createdAt: "2026-05-09T09:01:00.000Z", protectedUntil: "2026-06-08T09:01:00.000Z", recordsCaptured: 12840, status: "locked" },
    createdBy: "Марина Соколова",
    createdAt: "2026-05-09T08:55:00.000Z",
    startedAt: "2026-05-09T09:03:00.000Z",
    stats: { totalRows: 12840, creates: 10942, updates: 1411, rejected: 38, reviewRequired: 449, affectedRecords: 12353 },
  },
  {
    id: "job-2846",
    number: "IMP-2026-2846",
    name: "Остатки склада — инвентаризация май",
    entityType: "warehouse",
    status: "completed_with_warnings",
    stage: "report",
    progress: 100,
    file: {
      id: "file-769",
      name: "warehouse_stock_may.zip",
      fileType: "zip",
      sizeMb: 128.4,
      sheets: ["materials.csv", "balances.csv", "suppliers.csv"],
      checksum: "sha256:12aa...88c0",
      uploadedBy: "Олег Романов",
      uploadedAt: "2026-05-08T16:14:00.000Z",
      virusScan: "clean",
      chunkCount: 65,
    },
    dataSource: { id: "ds-wms", name: "Warehouse WMS export", entityType: "warehouse", origin: "zip", reliabilityScore: 91 },
    template: IMPORT_TEMPLATES[1],
    mappings: [],
    validationErrors: [],
    duplicates: [],
    preview: [],
    rollbackSnapshot: { id: "rb-2846", jobId: "job-2846", createdAt: "2026-05-08T16:40:00.000Z", protectedUntil: "2026-06-07T16:40:00.000Z", recordsCaptured: 48210, status: "available" },
    createdBy: "Олег Романов",
    createdAt: "2026-05-08T16:12:00.000Z",
    completedAt: "2026-05-08T16:48:00.000Z",
    stats: { totalRows: 48210, creates: 1830, updates: 46102, rejected: 11, reviewRequired: 267, affectedRecords: 47932 },
  },
];

export const QUEUE_WORKERS: QueueWorker[] = [
  { id: "w-parse-1", name: "Parser worker A", queue: "parse", status: "busy", throughputPerMinute: 8200, retryCount: 0 },
  { id: "w-val-2", name: "Validation worker B", queue: "validate", status: "busy", throughputPerMinute: 5100, retryCount: 1 },
  { id: "w-dedup-1", name: "AI dedupe worker", queue: "deduplicate", status: "busy", throughputPerMinute: 2300, retryCount: 0 },
  { id: "w-import-3", name: "Transactional importer", queue: "transactional_import", status: "idle", throughputPerMinute: 3600, retryCount: 0 },
  { id: "w-rb-1", name: "Rollback worker", queue: "rollback", status: "idle", throughputPerMinute: 1900, retryCount: 0 },
];

export const MDM_REFERENCES: MasterDataReference[] = [
  { id: "mdm-1", name: "Типы лифтов", domain: "elevator_types", records: 42, version: "2026.05.1", dependencies: ["elevators", "work_types"], usage: 12840, warnings: [] },
  { id: "mdm-2", name: "Производители", domain: "manufacturers", records: 118, version: "2026.05.3", dependencies: ["materials", "elevators"], usage: 31980, warnings: ["3 aliases require approval"] },
  { id: "mdm-3", name: "Материалы", domain: "materials", records: 8420, version: "2026.04.9", dependencies: ["warehouse", "work_orders"], usage: 923400, warnings: ["12 duplicate SKU candidates"] },
  { id: "mdm-4", name: "SLA категории", domain: "sla_categories", records: 16, version: "2026.05.2", dependencies: ["contracts", "objects"], usage: 842, warnings: [] },
  { id: "mdm-5", name: "Категории аварий", domain: "emergency_categories", records: 64, version: "2026.05.1", dependencies: ["dispatch", "analytics"], usage: 55100, warnings: ["1 inactive category used in active SLA rule"] },
];

export const PIPELINE_STEPS = [
  { key: "chunked_upload", name: "Chunked secure upload", description: "Multipart upload with checksum, MIME verification and resumable chunks." },
  { key: "virus_scan", name: "Virus scanning", description: "Files stay quarantined until malware scanning and file policy checks pass." },
  { key: "parse", name: "Streaming parse", description: "XLSX/CSV/ZIP parsed as streams; large sheets are split into row groups." },
  { key: "mapping", name: "AI mapping", description: "Column names, sample values and templates produce mapping confidence scores." },
  { key: "validation", name: "Async validation", description: "Required fields, data types, references, addresses, SKUs and broken relations." },
  { key: "dedupe", name: "Duplicate detection", description: "Factory numbers, addresses, customer names, material names and users are matched." },
  { key: "normalize", name: "Normalization", description: "Addresses, phones, SKU aliases, manufacturer aliases and SLA names are canonicalized." },
  { key: "transaction", name: "Transactional import", description: "Batches commit with rollback snapshots and partial-success boundaries." },
  { key: "report", name: "Report", description: "Signed report, audit events, affected records and rollback options are stored." },
];
