import type {
  AiValidationResult,
  DocumentRecord,
  MediaAlert,
  MediaFile,
  MediaGridRow,
  MediaRecommendation,
  MediaVersion,
  OfflineMediaCache,
  PdfReport,
  PhotoSession,
  RequirementTemplate,
  UploadQueueItem,
  MediaAnnotation,
} from "./types";

export const MEDIA_FILES: MediaFile[] = [
  {
    id: "media-1",
    kind: "photo",
    photoType: "before",
    title: "Before — кнопка вызова",
    objectId: "obj-sever",
    objectAddress: "БЦ Север",
    elevatorId: "el-sc88420",
    elevatorFactoryNumber: "SC-88420",
    nodeId: "node-cop",
    nodeName: "Пост приказов",
    workOrderId: "WO-2939",
    mechanicId: "mech-014",
    mechanicName: "Алексей Климов",
    attachmentEntity: "work_order",
    uploadStatus: "synced",
    aiStatus: "passed",
    createdAt: "2026-05-12T08:38:00.000Z",
    capturedAt: "2026-05-12T08:36:00.000Z",
    sizeMb: 3.8,
    mimeType: "image/jpeg",
    checksum: "sha256:before2939",
    storageKey: "s3://neolift-hot/2026/05/wo-2939/before.jpg",
    thumbnailKey: "thumbs/wo-2939/before.webp",
    storageTier: "hot",
    offlineCached: false,
    tags: ["before", "button", "work-order"],
    processing: [
      "received",
      "compressed",
      "thumbnail_ready",
      "exif_extracted",
      "ai_validated",
      "watermarked",
      "published",
    ],
  },
  {
    id: "media-2",
    kind: "photo",
    photoType: "after",
    title: "After — новая кнопка",
    objectId: "obj-sever",
    objectAddress: "БЦ Север",
    elevatorId: "el-sc88420",
    elevatorFactoryNumber: "SC-88420",
    nodeId: "node-cop",
    nodeName: "Пост приказов",
    workOrderId: "WO-2939",
    mechanicId: "mech-014",
    mechanicName: "Алексей Климов",
    attachmentEntity: "work_order",
    uploadStatus: "uploading",
    aiStatus: "pending",
    createdAt: "2026-05-12T08:49:00.000Z",
    capturedAt: "2026-05-12T08:48:00.000Z",
    sizeMb: 4.5,
    mimeType: "image/jpeg",
    checksum: "sha256:after2939",
    storageKey: "s3://neolift-hot/2026/05/wo-2939/after.jpg",
    thumbnailKey: "thumbs/wo-2939/after.webp",
    storageTier: "hot",
    offlineCached: true,
    tags: ["after", "button", "pending-ai"],
    processing: ["received", "compressed"],
  },
  {
    id: "media-3",
    kind: "photo",
    photoType: "removed_part",
    title: "Демонтированная кнопка",
    objectId: "obj-sever",
    objectAddress: "БЦ Север",
    elevatorId: "el-sc88420",
    elevatorFactoryNumber: "SC-88420",
    nodeId: "node-cop",
    nodeName: "Пост приказов",
    workOrderId: "WO-2939",
    mechanicId: "mech-014",
    mechanicName: "Алексей Климов",
    attachmentEntity: "material",
    uploadStatus: "queued",
    aiStatus: "warning",
    createdAt: "2026-05-12T08:51:00.000Z",
    capturedAt: "2026-05-12T08:50:00.000Z",
    sizeMb: 5.1,
    mimeType: "image/jpeg",
    checksum: "sha256:removed2939",
    storageKey: "s3://neolift-hot/2026/05/wo-2939/removed.jpg",
    thumbnailKey: "thumbs/wo-2939/removed.webp",
    storageTier: "hot",
    offlineCached: true,
    tags: ["removed-part", "quality-warning"],
    processing: ["received"],
  },
  {
    id: "media-4",
    kind: "photo",
    photoType: "emergency",
    title: "Авария — створка двери",
    objectId: "obj-kir18",
    objectAddress: "ул. Кирова, 18к2",
    elevatorId: "el-ot441121",
    elevatorFactoryNumber: "OT-441121",
    nodeId: "node-door",
    nodeName: "Дверной привод",
    workOrderId: "WO-2944",
    mechanicId: "mech-031",
    mechanicName: "Ирина Соколова",
    emergencyEventId: "em-771",
    attachmentEntity: "emergency_event",
    uploadStatus: "failed",
    aiStatus: "failed",
    createdAt: "2026-05-12T07:22:00.000Z",
    capturedAt: "2026-05-12T07:19:00.000Z",
    sizeMb: 6.4,
    mimeType: "image/jpeg",
    checksum: "sha256:door-emergency",
    storageKey: "s3://neolift-hot/2026/05/em-771/door.jpg",
    thumbnailKey: "thumbs/em-771/door.webp",
    storageTier: "hot",
    offlineCached: true,
    tags: ["emergency", "door", "retake-required"],
    processing: ["received"],
  },
  {
    id: "media-5",
    kind: "pdf",
    title: "Паспорт лифта SC-88420",
    objectId: "obj-sever",
    objectAddress: "БЦ Север",
    elevatorId: "el-sc88420",
    elevatorFactoryNumber: "SC-88420",
    attachmentEntity: "elevator",
    uploadStatus: "synced",
    aiStatus: "passed",
    createdAt: "2026-05-10T12:10:00.000Z",
    capturedAt: "2026-05-10T12:10:00.000Z",
    sizeMb: 18.2,
    mimeType: "application/pdf",
    checksum: "sha256:passport-sc88420",
    storageKey: "s3://neolift-warm/docs/sc-88420/passport.pdf",
    thumbnailKey: "thumbs/docs/sc-88420/passport.webp",
    storageTier: "warm",
    offlineCached: false,
    tags: ["passport", "pdf", "ocr-complete"],
    processing: ["received", "thumbnail_ready", "ocr_complete", "published"],
  },
  {
    id: "media-6",
    kind: "schematic",
    title: "Схема шкафа управления",
    objectId: "obj-sever",
    objectAddress: "БЦ Север",
    elevatorId: "el-sc88420",
    elevatorFactoryNumber: "SC-88420",
    nodeId: "node-controller",
    nodeName: "Шкаф управления",
    attachmentEntity: "node",
    uploadStatus: "synced",
    aiStatus: "manual_review",
    createdAt: "2026-05-11T16:40:00.000Z",
    capturedAt: "2026-05-11T16:40:00.000Z",
    sizeMb: 9.7,
    mimeType: "application/pdf",
    checksum: "sha256:schematic-controller",
    storageKey: "s3://neolift-warm/docs/sc-88420/controller-schematic.pdf",
    thumbnailKey: "thumbs/docs/sc-88420/schematic.webp",
    storageTier: "warm",
    offlineCached: true,
    tags: ["schematic", "restricted", "manual-review"],
    processing: ["received", "ocr_complete", "published"],
  },
];

export const PHOTO_SESSIONS: PhotoSession[] = [
  {
    id: "ps-1",
    workOrderId: "WO-2939",
    mechanicId: "mech-014",
    objectAddress: "БЦ Север",
    elevatorFactoryNumber: "SC-88420",
    scenario: "before_after",
    requiredPhotoTypes: ["before", "after", "removed_part"],
    capturedPhotoIds: ["media-1", "media-2", "media-3"],
    missingPhotoTypes: [],
    completion: 100,
    offline: true,
    startedAt: "2026-05-12T08:34:00.000Z",
    lastActivityAt: "2026-05-12T08:51:00.000Z",
  },
  {
    id: "ps-2",
    workOrderId: "WO-2944",
    mechanicId: "mech-031",
    objectAddress: "ул. Кирова, 18к2",
    elevatorFactoryNumber: "OT-441121",
    scenario: "emergency",
    requiredPhotoTypes: ["emergency", "node", "serial_plate"],
    capturedPhotoIds: ["media-4"],
    missingPhotoTypes: ["node", "serial_plate"],
    completion: 34,
    offline: false,
    startedAt: "2026-05-12T07:18:00.000Z",
    lastActivityAt: "2026-05-12T07:22:00.000Z",
  },
];

export const UPLOAD_QUEUE: UploadQueueItem[] = [
  {
    id: "uq-1",
    mediaFileId: "media-2",
    localIndexedDbKey: "idb://media/wo-2939/after",
    status: "uploading",
    progress: 64,
    retryCount: 0,
    chunkCount: 6,
    uploadedChunks: 4,
    priority: "high",
    network: "cellular",
  },
  {
    id: "uq-2",
    mediaFileId: "media-3",
    localIndexedDbKey: "idb://media/wo-2939/removed",
    status: "queued",
    progress: 0,
    retryCount: 1,
    nextRetryAt: "2026-05-12T09:05:00.000Z",
    chunkCount: 7,
    uploadedChunks: 0,
    priority: "normal",
    network: "offline",
  },
  {
    id: "uq-3",
    mediaFileId: "media-4",
    localIndexedDbKey: "idb://media/em-771/door",
    status: "failed",
    progress: 37,
    retryCount: 4,
    nextRetryAt: "2026-05-12T09:02:00.000Z",
    chunkCount: 9,
    uploadedChunks: 3,
    priority: "emergency",
    network: "cellular",
    error: "signed URL expired; recovery token required",
  },
];

export const DOCUMENTS: DocumentRecord[] = [
  {
    id: "doc-1",
    title: "Паспорт лифта SC-88420",
    kind: "passport",
    objectId: "obj-sever",
    elevatorId: "el-sc88420",
    mediaFileId: "media-5",
    version: 4,
    permission: "mechanic",
    ocrStatus: "complete",
    signedUrlTtlMinutes: 15,
  },
  {
    id: "doc-2",
    title: "Схема шкафа управления",
    kind: "schematic",
    objectId: "obj-sever",
    elevatorId: "el-sc88420",
    mediaFileId: "media-6",
    version: 2,
    permission: "restricted",
    ocrStatus: "complete",
    signedUrlTtlMinutes: 5,
  },
];

export const PDF_REPORTS: PdfReport[] = [
  {
    id: "pdf-1",
    reportType: "work_order",
    sourceEntityId: "WO-2939",
    status: "generating",
    pageCount: 6,
    mediaFileIds: ["media-1", "media-2", "media-3"],
  },
  {
    id: "pdf-2",
    reportType: "inspection",
    sourceEntityId: "INSP-118",
    status: "ready",
    pageCount: 18,
    mediaFileIds: ["media-5", "media-6"],
    generatedAt: "2026-05-11T18:05:00.000Z",
    exportedTo: "archive",
  },
];

export const MEDIA_ANNOTATIONS: MediaAnnotation[] = [
  {
    id: "ann-1",
    mediaFileId: "media-4",
    author: "AI validation",
    type: "box",
    label: "Темная область; требуется повторное фото",
    severity: "critical",
    createdAt: "2026-05-12T07:23:00.000Z",
  },
  {
    id: "ann-2",
    mediaFileId: "media-1",
    author: "Алексей Климов",
    type: "arrow",
    label: "Поврежденная кнопка до замены",
    severity: "info",
    createdAt: "2026-05-12T08:39:00.000Z",
  },
];

export const AI_VALIDATION_RESULTS: AiValidationResult[] = [
  {
    id: "ai-1",
    mediaFileId: "media-1",
    status: "passed",
    confidence: 96,
    checks: [
      { code: "blur", passed: true, message: "Резкость достаточная" },
      {
        code: "wrong_object",
        passed: true,
        message: "Объект совпадает с GPS/заказом",
      },
    ],
    recommendation: "Accept as before evidence",
    createdAt: "2026-05-12T08:39:00.000Z",
  },
  {
    id: "ai-2",
    mediaFileId: "media-3",
    status: "warning",
    confidence: 79,
    checks: [
      {
        code: "dark",
        passed: false,
        message: "Недостаточная освещенность детали",
      },
      { code: "duplicate", passed: true, message: "Дубликатов нет" },
    ],
    recommendation:
      "Mechanic can keep photo, but supervisor may request retake",
    createdAt: "2026-05-12T08:52:00.000Z",
  },
  {
    id: "ai-3",
    mediaFileId: "media-4",
    status: "failed",
    confidence: 91,
    checks: [
      { code: "dark", passed: false, message: "Фото аварии слишком темное" },
      {
        code: "missing_required",
        passed: false,
        message: "Нет фото узла и шильдика",
      },
    ],
    recommendation:
      "Block closure until retake and required emergency shots are attached",
    createdAt: "2026-05-12T07:23:00.000Z",
  },
];

export const OFFLINE_MEDIA_CACHE: OfflineMediaCache = {
  id: "omc-1",
  deviceId: "iphone-14-mech-014",
  mechanicId: "mech-014",
  mediaFileIds: ["media-2", "media-3", "media-6"],
  indexedDbUsedMb: 412,
  maxMb: 1024,
  pendingUploads: 2,
  lastBackgroundSyncAt: "2026-05-12T08:55:00.000Z",
  serviceWorkerState: "syncing",
};

export const MEDIA_VERSIONS: MediaVersion[] = [
  {
    id: "mv-1",
    mediaFileId: "media-1",
    version: 1,
    reason: "original",
    storageKey: "raw/wo-2939/before.heic",
    createdAt: "2026-05-12T08:36:00.000Z",
  },
  {
    id: "mv-2",
    mediaFileId: "media-1",
    version: 2,
    reason: "watermarked",
    storageKey: "processed/wo-2939/before-watermarked.webp",
    createdAt: "2026-05-12T08:38:00.000Z",
  },
];

export const REQUIREMENT_TEMPLATES: RequirementTemplate[] = [
  {
    id: "req-button",
    workType: "Замена кнопки",
    requiredPhotoTypes: ["before", "after", "removed_part"],
    minPhotos: 3,
    aiChecks: ["blur", "dark", "duplicate", "wrong_object"],
  },
  {
    id: "req-emergency-door",
    workType: "Авария двери",
    requiredPhotoTypes: ["emergency", "node", "serial_plate"],
    minPhotos: 3,
    aiChecks: ["blur", "dark", "wrong_object", "missing_required"],
  },
];

export const MEDIA_ALERTS: MediaAlert[] = [
  {
    id: "alert-1",
    title: "Emergency upload failed",
    description: "WO-2944 аварийное фото остановлено: signed URL expired",
    severity: "critical",
    type: "failed_upload",
  },
  {
    id: "alert-2",
    title: "Missing required shots",
    description: "Авария двери требует фото узла и шильдика",
    severity: "critical",
    type: "missing_photo",
  },
  {
    id: "alert-3",
    title: "AI quality warning",
    description: "Демонтированная кнопка снята при низкой освещенности",
    severity: "warning",
    type: "ai_validation",
  },
  {
    id: "alert-4",
    title: "Pending sync",
    description: "2 файла ожидают background sync из IndexedDB",
    severity: "warning",
    type: "pending_sync",
  },
];

export const MEDIA_RECOMMENDATIONS: MediaRecommendation[] = [
  {
    id: "rec-1",
    title: "Auto-generate WO-2939 act",
    description:
      "Before/after/removed-part комплект полный; можно собрать PDF акт",
    confidence: 94,
    category: "report_generation",
  },
  {
    id: "rec-2",
    title: "Retake emergency door photo",
    description: "AI обнаружил темный кадр и отсутствие обязательных ракурсов",
    confidence: 91,
    category: "defect_detection",
  },
  {
    id: "rec-3",
    title: "Move old passports to warm tier",
    description:
      "PDF паспорта старше 90 дней можно перевести в cheaper storage",
    confidence: 82,
    category: "storage_optimization",
  },
  {
    id: "rec-4",
    title: "OCR serial plate extraction",
    description: "Добавить smart OCR для шильдиков OTIS/KONE/SCHINDLER",
    confidence: 88,
    category: "ocr",
  },
];

export function buildMediaGridRows(): MediaGridRow[] {
  return MEDIA_FILES.map((media) => ({
    media,
    session: PHOTO_SESSIONS.find(
      (session) =>
        session.capturedPhotoIds.includes(media.id) ||
        session.workOrderId === media.workOrderId,
    ),
    ai: AI_VALIDATION_RESULTS.find((result) => result.mediaFileId === media.id),
    queue: UPLOAD_QUEUE.find((item) => item.mediaFileId === media.id),
  }));
}
