import type {
  ConflictRecord,
  DeltaUpdate,
  DeviceState,
  FailedUpload,
  LocalDraft,
  LocalMediaCache,
  OfflineAuditLog,
  OfflineQueueItem,
  PendingOperation,
  RetryPolicy,
  SyncDashboardRow,
  SyncEvent,
  SyncSession,
  SyncSnapshot,
} from "./types";

export const DEVICE_STATE: DeviceState = {
  id: "dev-iphone-14-mech-014",
  deviceName: "iPhone 14 · Алексей",
  mechanicId: "mech-014",
  authorized: true,
  networkQuality: "unstable",
  battery: 68,
  storageUsedMb: 1840,
  storageLimitMb: 4096,
  lastSeenAt: "2026-05-12T09:12:00.000Z",
  websocket: "reconnecting",
  serviceWorker: "active",
  backgroundSync: "running",
};

export const OFFLINE_QUEUE: OfflineQueueItem[] = [
  {
    id: "oq-1",
    operationId: "op-1",
    entityType: "work_order",
    entityId: "WO-2944",
    priority: "emergency",
    status: "syncing",
    createdAt: "2026-05-12T08:40:00.000Z",
    lastAttemptAt: "2026-05-12T09:11:20.000Z",
    retryCount: 1,
    payloadBytes: 18420,
    encrypted: true,
    idempotencyKey: "idem-wo-2944-close",
  },
  {
    id: "oq-2",
    operationId: "op-2",
    entityType: "photo",
    entityId: "media-4",
    priority: "media",
    status: "failed",
    createdAt: "2026-05-12T07:22:00.000Z",
    lastAttemptAt: "2026-05-12T09:10:00.000Z",
    retryCount: 4,
    nextRetryAt: "2026-05-12T09:16:00.000Z",
    payloadBytes: 6400000,
    encrypted: true,
    idempotencyKey: "idem-media-4",
  },
  {
    id: "oq-3",
    operationId: "op-3",
    entityType: "signature",
    entityId: "sig-771",
    priority: "signature",
    status: "queued",
    createdAt: "2026-05-12T08:55:00.000Z",
    retryCount: 0,
    payloadBytes: 92000,
    encrypted: true,
    idempotencyKey: "idem-sig-771",
  },
  {
    id: "oq-4",
    operationId: "op-4",
    entityType: "material",
    entityId: "mat-dr44",
    priority: "material",
    status: "conflict",
    createdAt: "2026-05-12T08:57:00.000Z",
    lastAttemptAt: "2026-05-12T09:08:00.000Z",
    retryCount: 2,
    payloadBytes: 7400,
    encrypted: true,
    idempotencyKey: "idem-writeoff-dr44",
  },
  {
    id: "oq-5",
    operationId: "op-5",
    entityType: "inspection",
    entityId: "insp-118",
    priority: "work_order",
    status: "queued",
    createdAt: "2026-05-12T09:04:00.000Z",
    retryCount: 0,
    payloadBytes: 22800,
    encrypted: true,
    idempotencyKey: "idem-insp-118",
  },
];

export const PENDING_OPERATIONS: PendingOperation[] = [
  {
    id: "op-1",
    entityType: "work_order",
    action: "close",
    entityId: "WO-2944",
    workOrderId: "WO-2944",
    priority: "emergency",
    status: "syncing",
    baseVersion: 12,
    localVersion: 13,
    serverVersion: 12,
    createdBy: "Алексей Климов",
    createdAt: "2026-05-12T08:40:00.000Z",
    localPatchSummary: "Закрытие аварии, результат работ, runtime note",
  },
  {
    id: "op-2",
    entityType: "photo",
    action: "upload",
    entityId: "media-4",
    workOrderId: "WO-2944",
    priority: "media",
    status: "failed",
    baseVersion: 1,
    localVersion: 2,
    createdBy: "Алексей Климов",
    createdAt: "2026-05-12T07:22:00.000Z",
    localPatchSummary: "Аварийное фото дверного привода, 9 chunks",
  },
  {
    id: "op-3",
    entityType: "signature",
    action: "sign",
    entityId: "sig-771",
    workOrderId: "WO-2944",
    priority: "signature",
    status: "queued",
    baseVersion: 3,
    localVersion: 4,
    createdBy: "Клиент БЦ Север",
    createdAt: "2026-05-12T08:55:00.000Z",
    localPatchSummary: "Подпись клиента под актом выполненных работ",
  },
  {
    id: "op-4",
    entityType: "material",
    action: "write_off",
    entityId: "mat-dr44",
    workOrderId: "WO-2944",
    priority: "material",
    status: "conflict",
    baseVersion: 18,
    localVersion: 19,
    serverVersion: 20,
    createdBy: "Алексей Климов",
    createdAt: "2026-05-12T08:57:00.000Z",
    localPatchSummary: "Списание 2 роликов DR-44 из мобильного склада",
  },
  {
    id: "op-5",
    entityType: "inspection",
    action: "update",
    entityId: "insp-118",
    workOrderId: "WO-2951",
    priority: "work_order",
    status: "queued",
    baseVersion: 5,
    localVersion: 6,
    createdBy: "Ирина Соколова",
    createdAt: "2026-05-12T09:04:00.000Z",
    localPatchSummary: "ППР чеклист, замечание по направляющим",
  },
];

export const FAILED_UPLOADS: FailedUpload[] = [
  {
    id: "fu-1",
    mediaId: "media-4",
    workOrderId: "WO-2944",
    chunksTotal: 9,
    chunksUploaded: 3,
    lastError: "network timeout after signed URL refresh",
    retryPolicyId: "rp-media",
    resumableToken: "resume-media-4-3of9",
    priority: "media",
  },
  {
    id: "fu-2",
    mediaId: "media-8",
    workOrderId: "WO-2951",
    chunksTotal: 5,
    chunksUploaded: 4,
    lastError: "weak network throttled background sync",
    retryPolicyId: "rp-wifi",
    resumableToken: "resume-media-8-4of5",
    priority: "media",
  },
];

export const LOCAL_DRAFTS: LocalDraft[] = [
  {
    id: "draft-1",
    entityType: "work_order",
    entityId: "WO-2944",
    title: "Авария двери · БЦ Север",
    completion: 92,
    dirtyFields: ["result", "materials", "signature", "photos"],
    encryptedBlobKey: "idb://drafts/wo-2944",
    updatedAt: "2026-05-12T08:59:00.000Z",
    expiresAt: "2026-05-19T08:59:00.000Z",
  },
  {
    id: "draft-2",
    entityType: "inspection",
    entityId: "insp-118",
    title: "ППР · ул. Кирова 18к2",
    completion: 64,
    dirtyFields: ["checklist", "notes"],
    encryptedBlobKey: "idb://drafts/insp-118",
    updatedAt: "2026-05-12T09:05:00.000Z",
    expiresAt: "2026-05-19T09:05:00.000Z",
  },
];

export const CONFLICT_RECORDS: ConflictRecord[] = [
  {
    id: "conf-1",
    entityType: "material",
    entityId: "mat-dr44",
    workOrderId: "WO-2944",
    status: "diff_ready",
    localVersion: 19,
    serverVersion: 20,
    localChangedBy: "Алексей Климов offline",
    serverChangedBy: "Олег Романов warehouse",
    detectedAt: "2026-05-12T09:08:00.000Z",
    suggestedResolution:
      "Merge mechanic write-off with server reservation and request warehouse approval",
    diff: [
      {
        field: "reserved",
        local: "-2 mobile stock",
        server: "+2 reserved by warehouse",
        policy: "manual",
      },
      { field: "available", local: "1", server: "0", policy: "server_wins" },
      {
        field: "workOrderStatus",
        local: "ready_to_close",
        server: "materials_pending",
        policy: "manual",
      },
    ],
  },
  {
    id: "conf-2",
    entityType: "work_order",
    entityId: "WO-2951",
    workOrderId: "WO-2951",
    status: "mechanic_review",
    localVersion: 6,
    serverVersion: 7,
    localChangedBy: "Ирина Соколова offline",
    serverChangedBy: "Диспетчер Мария",
    detectedAt: "2026-05-12T09:09:00.000Z",
    suggestedResolution:
      "Keep dispatcher SLA change, merge mechanic checklist notes",
    diff: [
      {
        field: "slaWindow",
        local: "16:00",
        server: "14:30",
        policy: "server_wins",
      },
      {
        field: "checklist.notes",
        local: "шум направляющих",
        server: "",
        policy: "client_wins",
      },
    ],
  },
];

export const SYNC_SESSIONS: SyncSession[] = [
  {
    id: "sync-1",
    deviceId: "dev-iphone-14-mech-014",
    mechanicId: "mech-014",
    mode: "emergency",
    status: "running",
    startedAt: "2026-05-12T09:10:00.000Z",
    uploaded: 3,
    downloaded: 12,
    conflicts: 1,
    networkQuality: "unstable",
  },
  {
    id: "sync-0",
    deviceId: "dev-iphone-14-mech-014",
    mechanicId: "mech-014",
    mode: "delta",
    status: "completed",
    startedAt: "2026-05-12T07:58:00.000Z",
    completedAt: "2026-05-12T07:59:18.000Z",
    uploaded: 8,
    downloaded: 44,
    conflicts: 0,
    networkQuality: "online",
  },
];

export const LOCAL_MEDIA_CACHE: LocalMediaCache = {
  id: "lmc-1",
  deviceId: "dev-iphone-14-mech-014",
  mediaCount: 28,
  usedMb: 920,
  maxMb: 2048,
  compressionQueue: 3,
  uploadQueue: 5,
  oldestUnsyncedAt: "2026-05-12T07:22:00.000Z",
  survivesRestart: true,
};

export const RETRY_POLICIES: RetryPolicy[] = [
  {
    id: "rp-emergency",
    name: "Emergency operations",
    strategy: "priority_boost",
    maxRetries: 20,
    baseDelaySeconds: 5,
    maxDelaySeconds: 120,
    requiresWifi: false,
    pausesOnWeakNetwork: false,
  },
  {
    id: "rp-media",
    name: "Resumable media chunks",
    strategy: "network_aware",
    maxRetries: 12,
    baseDelaySeconds: 30,
    maxDelaySeconds: 900,
    requiresWifi: false,
    pausesOnWeakNetwork: true,
  },
  {
    id: "rp-default",
    name: "Default exponential backoff",
    strategy: "exponential_backoff",
    maxRetries: 8,
    baseDelaySeconds: 15,
    maxDelaySeconds: 600,
    requiresWifi: false,
    pausesOnWeakNetwork: false,
  },
  {
    id: "rp-wifi",
    name: "Large file Wi-Fi recovery",
    strategy: "network_aware",
    maxRetries: 10,
    baseDelaySeconds: 60,
    maxDelaySeconds: 1800,
    requiresWifi: true,
    pausesOnWeakNetwork: true,
  },
];

export const DELTA_UPDATES: DeltaUpdate[] = [
  {
    id: "du-1",
    entityType: "work_order",
    cursor: "wo-cursor-2026-05-12T09:10Z",
    serverVersion: 8842,
    changedAt: "2026-05-12T09:10:00.000Z",
    records: 14,
    applied: true,
  },
  {
    id: "du-2",
    entityType: "material",
    cursor: "mat-cursor-2026-05-12T09:11Z",
    serverVersion: 388,
    changedAt: "2026-05-12T09:11:00.000Z",
    records: 8,
    applied: false,
  },
  {
    id: "du-3",
    entityType: "document",
    cursor: "doc-cursor-2026-05-12T09:12Z",
    serverVersion: 129,
    changedAt: "2026-05-12T09:12:00.000Z",
    records: 3,
    applied: true,
  },
];

export const SYNC_SNAPSHOTS: SyncSnapshot[] = [
  {
    id: "snap-1",
    deviceId: "dev-iphone-14-mech-014",
    cursor: "snapshot-2026-05-12-am",
    capturedAt: "2026-05-12T06:30:00.000Z",
    workOrders: 42,
    elevators: 188,
    objects: 64,
    materials: 1240,
    documents: 320,
    checksum: "sha256:snapshot-am-014",
  },
];

export const SYNC_EVENTS: SyncEvent[] = [
  {
    id: "se-1",
    sessionId: "sync-1",
    type: "network_changed",
    message: "Network changed from offline to unstable LTE",
    severity: "warning",
    createdAt: "2026-05-12T09:10:01.000Z",
  },
  {
    id: "se-2",
    sessionId: "sync-1",
    type: "sync_started",
    message: "Emergency priority sync started by Background Sync API",
    severity: "info",
    createdAt: "2026-05-12T09:10:03.000Z",
  },
  {
    id: "se-3",
    sessionId: "sync-1",
    type: "operation_sent",
    message: "WO-2944 close operation sent with idempotency key",
    severity: "info",
    createdAt: "2026-05-12T09:11:20.000Z",
  },
  {
    id: "se-4",
    sessionId: "sync-1",
    type: "conflict_detected",
    message: "Material write-off conflict detected for DR-44",
    severity: "critical",
    createdAt: "2026-05-12T09:08:00.000Z",
  },
  {
    id: "se-5",
    sessionId: "sync-1",
    type: "retry_scheduled",
    message: "media-4 chunk upload scheduled after signed URL recovery",
    severity: "warning",
    createdAt: "2026-05-12T09:12:00.000Z",
  },
];

export const OFFLINE_AUDIT_LOGS: OfflineAuditLog[] = [
  {
    id: "log-1",
    deviceId: "dev-iphone-14-mech-014",
    actor: "Алексей Климов",
    action: "offline_update",
    entityType: "work_order",
    entityId: "WO-2944",
    timestamp: "2026-05-12T08:40:00.000Z",
    hash: "hash-001",
    previousHash: "hash-000",
  },
  {
    id: "log-2",
    deviceId: "dev-iphone-14-mech-014",
    actor: "Алексей Климов",
    action: "capture_signature",
    entityType: "signature",
    entityId: "sig-771",
    timestamp: "2026-05-12T08:55:00.000Z",
    hash: "hash-002",
    previousHash: "hash-001",
  },
  {
    id: "log-3",
    deviceId: "dev-iphone-14-mech-014",
    actor: "sync-engine",
    action: "conflict_detected",
    entityType: "material",
    entityId: "mat-dr44",
    timestamp: "2026-05-12T09:08:00.000Z",
    hash: "hash-003",
    previousHash: "hash-002",
  },
];

export const DEXIE_TABLES = [
  "workOrders",
  "elevators",
  "objects",
  "materials",
  "photos",
  "documents",
  "drafts",
  "signatures",
  "pendingOperations",
  "offlineQueue",
  "conflictRecords",
  "syncEvents",
  "auditLogs",
] as const;

export const PRIORITY_ORDER = [
  "emergency",
  "work_order",
  "signature",
  "material",
  "media",
  "analytics",
] as const;

export function buildSyncDashboardRows(): SyncDashboardRow[] {
  return PENDING_OPERATIONS.map((operation) => ({
    operation,
    queue: OFFLINE_QUEUE.find((item) => item.operationId === operation.id),
    conflict: CONFLICT_RECORDS.find(
      (conflict) => conflict.entityId === operation.entityId,
    ),
  }));
}
